global:
  smtp_smarthost: smtp.gmail.com:587
  smtp_auth_password_file: '/etc/alertmanager/smtp_auth_password'
  smtp_from: your_mail@gmail.com
  smtp_auth_username: your_mail@gmail.com
  smtp_auth_identity: your_mail@gmail.com

templates:
- '/etc/alertmanager/templates/*.tmpl'

route:
  receiver: "discord-alerts"
  group_by: [alertname]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 5m
  routes:
    - match:
        severity: critical
      receiver: "discord-critical"
      group_wait: 5s
      repeat_interval: 2m
    - match:
        severity: warning
      receiver: "discord-alerts"

receivers:
  - name: "discord-alerts"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '{{ template "discord.title" . }}'
        text: '{{ template "discord.text" . }}'
        
  - name: "discord-critical"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1378468656245117059/y2NYQi4z6clqKxnk4aywPkmYX8Ot_o_7Do4Hcj1Ye0ZWsQJpMB4HBBhAuUSyzxZv7TRA/slack"
        send_resolved: true
        title: '🔥 CRITICAL ALERT'
        text: '{{ template "discord.critical" . }}'