global:
  scrape_interval: 2s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - 'rules/1.basic.yml'
  #- 'rules/2.absent.yml'
  #- 'rules/3.group.yml'
  #- 'rules/4.templating.yml'
  # restart prometheus

scrape_configs:
  - job_name: 'ecommerce-app'
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/metrics'
    scrape_interval: 2s
    scrape_timeout: 1s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
