groups:
  - name: ecommerce_system_alerts
    interval: 5s
    rules:
      # High CPU Usage Alert
      - alert: HighCPUUsage
        expr: ecommerce_cpu_usage_percent > 80
        for: 30s
        labels:
          severity: critical
          service: system
        annotations:
          summary: "E-commerce System High CPU Usage"
          description: "CPU usage is {{ $value }}% which exceeds the 80% threshold for more than 30 seconds."
          
      # High Memory Usage Alert
      - alert: HighMemoryUsage
        expr: (ecommerce_memory_usage_bytes{type="used_percent"} > 85)
        for: 30s
        labels:
          severity: critical
          service: system
        annotations:
          summary: "E-commerce System High Memory Usage"
          description: "Memory usage is {{ $value }}% which exceeds the 85% threshold for more than 30 seconds."
          
      # Low Memory Alert
      - alert: LowMemoryWarning
        expr: (ecommerce_memory_usage_bytes{type="used_percent"} > 70)
        for: 1m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "E-commerce System Memory Warning"
          description: "Memory usage is {{ $value }}% which exceeds the 70% threshold for more than 1 minute."

  - name: ecommerce_business_alerts
    interval: 5s
    rules:
      # High Login Rate Alert (10 users in 10 seconds)
      - alert: HighLoginRate
        expr: increase(ecommerce_user_logins_total[10s]) > 10
        for: 0s
        labels:
          severity: warning
          service: authentication
        annotations:
          summary: "High User Login Rate Detected"
          description: "{{ $value }} user logins detected in the last 10 seconds, exceeding the threshold of 10 logins."
          
      # Excessive Payment Rate Alert (5 payments in 5 seconds)
      - alert: HighPaymentRate
        expr: increase(ecommerce_payments_processed_total[5s]) > 5
        for: 0s
        labels:
          severity: warning
          service: payment
        annotations:
          summary: "High Payment Processing Rate"
          description: "{{ $value }} payments processed in the last 5 seconds, exceeding the threshold of 5 payments."
          
      # Payment Error Rate Alert
      - alert: HighPaymentErrorRate
        expr: rate(ecommerce_payment_errors_total[1m]) > 0.1
        for: 30s
        labels:
          severity: critical
          service: payment
        annotations:
          summary: "High Payment Error Rate"
          description: "Payment error rate is {{ $value }} errors per second over the last minute."
          
      # Application Error Rate Alert
      - alert: HighErrorRate
        expr: rate(ecommerce_errors_total[5m]) > 0.05
        for: 1m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High Application Error Rate"
          description: "Application error rate is {{ $value }} errors per second over the last 5 minutes."

  - name: ecommerce_availability_alerts
    interval: 10s
    rules:
      # Service Down Alert
      - alert: ServiceDown
        expr: up{job="ecommerce-app"} == 0
        for: 10s
        labels:
          severity: critical
          service: application
        annotations:
          summary: "E-commerce Application Down"
          description: "The e-commerce application has been down for more than 10 seconds."
          
      # High Response Time Alert
      - alert: HighResponseTime
        expr: ecommerce_avg_response_time_ms > 2000
        for: 1m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "High Response Time"
          description: "Average response time is {{ $value }}ms, exceeding the 2000ms threshold."
